### ISSUE TITLE
Does not open anymore

### ISSUE THREAD

**Issue by stefonarch** [lxde/lx-control-center#3]
It's looking for a non-existent file

```
stef@arch:~/git/lx-control-center$ python lx-control-center
ERROR:root:Utils.load_object(ini): error, when loading /usr/share/xsessions/lxqt/desktop.conf as a ini file
Traceback (most recent call last):
  File "lx-control-center", line 25, in <module>
    app.run()
  File "/home/stef/git/lx-control-center/LXControlCenter/runner.py", line 108, in run
    from LXControlCenter.widgets.qt5 import Qt5App
  File "/home/stef/git/lx-control-center/LXControlCenter/widgets/qt5.py", line 27, in <module>
    from .common import UI
ModuleNotFoundError: No module named 'LXControlCenter.widgets.common'

```

**Comment by gilir** [comment]
Thanks for your bug report.

I think the error message is harmless, but it crashed because it tried to use the Qt frontend, which is a big work-in-progress.

If you start with "python lx-control-center --ui GTK3", it should works.

I'll fix the default behavior to avoid this crash

**Comment by stefonarch** [comment]
Works now well.
