### ISSUE TITLE
GTK2 UI errors

### ISSUE THREAD

**Issue by micrococo** [lxde/lx-control-center#4]
Hi.

When running LX-Control-Center using the GTK2 user interface, there are some errors:
```
$ lx-control-center -u GTK2 
WARNING:root:Utils.__get_path : Can't find an existing file for relative path  None
ERROR:root:Utils.load_object(ini): error, when loading None as a ini file
/usr/lib64/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You  have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with  introspection some of the interfaces and API will fail.  As such this is not  supported by the pygobject development team and we encourage you to port your  app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk  2.0   
  warnings.warn(warn_msg, RuntimeWarning) 
WARNING:root:Utils.__get_path : Can't find an existing file for relative path  None 
ERROR:root:Utils.load_object(ini): error, when loading None as a ini file WARNING:root:Utils.__get_path : Can't find an existing file for relative path  None
ERROR:root:Utils.load_object(ini): error, when loading None as a ini file
```

These error don't prevent the application from starting. But when you click Preferences there is an error and the Preferences widget shows nothing:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/LXControlCenter/base.py", line 672, in on_pref_mode_menu_click
    self.draw_ui()
  File "/usr/lib/python2.7/site-packages/LXControlCenter/widgets/gtk2.py", line 56, in draw_ui
    self.build_pref_view()   File "/usr/lib/python2.7/site-packages/LXControlCenter/widgets/gtk2.py", line 116, in build_pref_view
    conf_counter = self.add_combobox_text(self.frontend_control_center_setting, configuration_grid, conf_counter)
  File "/usr/lib/python2.7/site-packages/LXControlCenter/widgets/gtkcommon.py", line 125, in add_combobox_text
    self.attach_widget(position, combo_label, combo, grid)
  File "/usr/lib/python2.7/site-packages/LXControlCenter/widgets/gtkcommon.py", line 189, in attach_widget
    widget.set_alignment(0.5)
AttributeError: 'ComboBox' object has no attribute 'set_alignment'
```

I didn't report this before because I wasn't sure whether you had finished issue #2 or not.

Greetings.

**Comment by gilir** [comment]
Thank you for the report, and sorry for the unstability, I'm still trying to make the code easier to maintain. I'll check this as soon as I can.

**Comment by micrococo** [comment]
Oh, no, don't worry. I understand that the program is under development and bugs are unavoidable. Thanks to you for taking the time to develop the application and fix the bugs. There is no hurry at all :)
